### ISSUE TITLE
||| Submit Feature Requests Here |||

### ISSUE THREAD

**Issue by allusive-dev** [allusive-dev/compfy#17]
This discussion is for requesting features to be added.

**Please try to be as explicit as possible about the feature you want added to make it easier for me to understand what exactly you are wanting.**

**If you see a feature request that you also want please leave a reaction on the comment so that I know more people want it.**

Lastly I cannot guarantee every request will be added, but I will try my best to add as many as I can.

**Comment by allusive-dev** [comment]
Until further notice feature requests will not be worked on until all the currently active WM specific issues are solved.

Sorry for the delay and hope to be back at new features soon!

(You can still submit a feature request, I just won't be able to work on it until further notice)

**Comment by Sinomor** [comment]
add an option for blur all windows, because blur-rule works poorly in some cases

**Comment by allusive-dev** [comment]
Hey @Sinomor 
I added that feature as requested!
Please see the [1.4.0 release notes](https://github.com/allusive-dev/picom-allusive/releases/tag/1.4.0) for more information!
