### ISSUE TITLE
Maximized Windows Don't Fade When Closed [XFCE]

### ISSUE THREAD

**Issue by aisneto** [allusive-dev/compfy#40]
Hello! First of all, congratulations on your compositor! This has been the best fork of Picom I've used so far. The animations and transitions are just perfect.

However, there is an issue that I've been experiencing with all Picom-related forks: maximized windows simply do not fade when closing. They close abruptly, as if the fade effect has not been set. So far, this has been the only issue I've had regarding janking when using your compositor. If it could be possible to fix this, it would be just perfect.

I am using version 1.6.0, built with Meson and Ninja.
Debian 11
XFCE (with the compositor turned off, of course)

**Comment by allusive-dev** [comment]
@aisneto 
Thanks, I'm glad you have been enjoying it.
With your issue though, is it possible for you to attach or explain an example of these "maximized windows"?
I assumed you meant full screen but I just wanted to check.

**Comment by aisneto** [comment]
That's right! I'm attaching an image of the type of window that doesn't fade when closing (even though it fades when opening) 

![Captura de tela_2023-11-15_20-07-53](https://github.com/allusive-dev/compfy/assets/105523584/f6bb5b85-a916-4bbf-8bed-5d8f2fd5a2dc)

**Comment by allusive-dev** [comment]
@aisneto 
Thanks for that.
As I can see it is a maximized layout not just the window being full-screen(since it would overlap the bar if it was full-screen).
I haven't seen or touched XFCE before and I do not think this is a configuration issue, but just in case can you please send your configuration? (You may need to rename it to `compfy.conf.txt` to upload it)
Would you also be able to quickly check and confirm with me that it is ONLY maximized windows that are not fading out?

**Comment by aisneto** [comment]
Hello again! I've identified our issue.

As evident in my latest screenshot, I configured my XFCE window rules to conceal titles and borders when maximized. Strangely, upon disabling this setting, closing maximized windows triggered the fade effect as expected. Any insights on why this might be happening? While I'd like to maintain a borderless look, I value the smooth and consistent fade effect more. Any suggestions or thoughts would be appreciated.

**Comment by allusive-dev** [comment]
> I configured my XFCE window rules to conceal titles and borders when maximized. Strangely, upon disabling this setting, closing maximized windows triggered the fade effect as expected.

So XFCE was the culprit. Best thing I can guess is for some reason the window gets passed new X flags when the frame is invisible, causing it to cancel fading out for some reason.

At the moment their probably is not a huge amount I can do. Would you be able to play around with your settings some more to see if you get any new results?
