### ISSUE TITLE
blur not working in awesomewm-git

### ISSUE THREAD

**Issue by daricoder** [allusive-dev/compfy#42]
<-- Please fill in all the forms below that are relevant then delete this line -->

**What is the issue**
The blur settings do not work for me as a result I have semi-transparent windows.
Shadows, animations and fading work very well.

**What did you expect**
I expected the blur to work the same as in picom

**Relevant Images or Videos:**

**Your configuration**
my test config is:
#.config/compfy/compfy.conf
fading = true;
blur-background=true;
blur-method = "dual_kawase";
backend="glx";
blur-strength=6;
active-opacity=1;
frame-opacity=1;
blur-kern = "3x3box";
blur-background-frame = false;
blur-background-fixed = true;
vsync = true;
glx-no-stencil = true;

**Package Version:**
v1.7.0
**Build Method:**
meson setup -Dupdate_checks=true . build
-
**WM:**
wm: awesomewm (git version: awesome v4.3-1606-g0e5fc4575-dirty (Too long) )

**Comment by allusive-dev** [comment]
Yet another person who has not read the documentation.
Sigh
Please read this and close the issue once everything is working. Thanks
https://github.com/allusive-dev/compfy/wiki/6.-Blur#blur-whitelist

**Comment by daricoder** [comment]
thanks works like a charm! 😀.

**Comment by allusive-dev** [comment]
Glad to hear!
