### ISSUE TITLE
Expected/Normal RAM Usage?

### ISSUE THREAD

**Issue by pienapin** [allusive-dev/compfy#44]
Not really an issue, I just want to know, what is the normal or expected RAM usage of compfy?
Because it is using 2.93 GiB memory on my computer right now, opening two windows of Firefox, some terminals, spotify, and polybar. Is that normal or a problem?

**Comment by allusive-dev** [comment]
Hey @pienapin 
I opened the same apps you described on mt system and I am using the same amount of RAM.
But if you take a look at something like `htop` or `btop` you may see something similar to this.

![image](https://github.com/allusive-dev/compfy/assets/99632976/e5443981-0eb8-4e4b-a409-edac638c8d38)

Either way that amount of RAM usage is fairly normal, hopefully in future updates this will be improved.

**Comment by pienapin** [comment]
wait, I mean the compfy alone using that much amount of ram, that means there is problem on my side(?)
![image](https://github.com/allusive-dev/compfy/assets/80519948/739563d9-b2f4-4930-9e44-99af19dd7e7a)

I don't use the '-b' flag like you tho

**Comment by allusive-dev** [comment]
@pienapin 
Ah ok that is a bit of an issue.
Thanks for letting me know about that. I'll update the FAQ

**Comment by pienapin** [comment]
turns out that the RAM usage was low when I tried with flag because I just started it. The memory usage is growing overtime even with the flag (I let it runs for 10 hours and the memory usage is 2.8 GiB). Is it memory leak?

**Comment by allusive-dev** [comment]
@pienapin 
It could be a memory leak yes.
I cannot fix this at the moment however hopefully some updates will be released in the near future fixing memory leaks and another few performance issues.
