### ISSUE TITLE
Open and close animations look weird

### ISSUE THREAD

**Issue by daricoder** [allusive-dev/compfy#45]
**What is the issue**
Open and close animations clip the window and the blurred background pops out while the open and close animations are performed

**What did you expect**
I expected the windows to expand and shrink correctly according to the open and close animation.

It seems that the window does not follow the animation of the blurred background with respect to the size but with the positions causing the clipping when it shrinks and the overflow when the background expands.

**Relevant Images or Videos:**
https://github.com/allusive-dev/compfy/assets/64455469/28fad5e1-dce3-4114-890e-393b0bce12f9

configuration:
blur-background=true;
blur-whitelist=false

blur-method = "dual_kawase";
backend="glx";
blur-strength=3;
active-opacity=1;
frame-opacity=1;
blur-kern = "3x3box";

shadow = true;
shadow-radius = 20;
shadow-opacity = 0.2
shadow-offset-x = -18;
shadow-offset-y = -18;

fading = true;

animations=true
animation-for-open-window="zoom"
animation-stiffness = 110
animation-window-mass = 0.8
animation-dampening = 5

corner-radius = 12

**Package Version:**
v1.7.0

**Build Method:**
meson setup -Dupdate_checks=true . build

**WM:**
awesomewm-git

**Comment by allusive-dev** [comment]
@daricoder 
That is your settings.
> animation-window-mass = 0.8
> animation-dampening = 5
These two settings are the main causes of that great of an animation adjustment.
You don't need to make an issue about this, please read the documentation.
