### ISSUE TITLE
blur background not working

### ISSUE THREAD

**Issue by snakebite-382** [allusive-dev/compfy#48]
**Configuration**
running compfy with: 

`compfy -b --config ~/.config/compfy/compfy.conf --backend glx`

blur settings
```
blur = true;
blur-method="kernel";
blur-exclude = [
    "class_g = 'firefox'"
];
blur-whitelist=false;
```

**Package Version:**
v1.7.0
**Build Method:**
Installed from AUR with pacman
**WM:**
herbstluftwm

**Comment by allusive-dev** [comment]
@snakebite-382 
The option is not `blur = true` it is `blur-background = true`
Please make sure to read the documentation more fully before creating an issue.

**Comment by allusive-dev** [comment]
As a side note you don't need to specify that config path as that is the default path.
