### ISSUE TITLE
Override animation type for specific windows

### ISSUE THREAD

**Issue by Myvillithdar** [allusive-dev/compfy#55]
I can write rules to exclude windows from open/close animations, but I think it'd be cool to be able to set different animations for certain windows.  I'm imagining a configuration syntax based on `opacity-rule` like the following (this could maybe replace `animation-open-exclude` and `animation-unmap-exclude`):
```
animation-open-rule = [
  "slide-down:window_type = 'tooltip'",
  "none:class_g = 'Conky'"
]

animation-unmap-rule = [
  "slide-up:window_type = 'tooltip'",
  "none:class_g = 'Conky'"
]
```

**Comment by allusive-dev** [comment]
This was actually implemented at one point but never reached the repository. Sorry for that!
