### ISSUE TITLE
Animations causes really high power usage

### ISSUE THREAD

**Issue by Cae-lim** [allusive-dev/compfy#57]
**What is the issue**
Turning on animations causes a 2-4 watt increase in power usage reported by powertop. Disabling animations drops compfy from being the highest power consumption (idle without running something power hungry like a game) to being fairly lightweight. Animations don't just make the stats worse they decrease the amount of battery life I actually get.

**What I've tried**
* Disabling & re-enabling other settings (only animations had noticeable changes
* Different Backends
* enabling/disabling wm patch option
* comparing to picom (similar performance in regards to power consumption without animations 

**Relevant info**
Compfy version 1.7.2 installed with pacman

Neofetch for sysinfo:
![neofetch](https://github.com/allusive-dev/compfy/assets/56897435/9f62eeef-0799-4c3c-8c26-acede47e351f)

Power top without animations
![ptNoAnim](https://github.com/allusive-dev/compfy/assets/56897435/8a311862-a191-4162-916e-0c55f22d5c42)
t animations

Power Top with animations
![ptAnim](https://github.com/allusive-dev/compfy/assets/56897435/acb2a045-5161-42cc-bd32-0ca19a51d637)

My Config
```
wm-support = "herb"

#################################
#         ANIMATIONS            #
#################################

animations = true;
animation-stiffness = 120;
animation-window-mass = 0.5;
animation-dampening = 12;
animation-clamping = false;
animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";

animation-open-exclude = [
    "class_g = 'Polybar'"
]

animation-unmap-exclude = [
    "class_g = 'Polybar'"
]

#################################
#           Corners             #
#################################

corner-radius = 14;
rounded-corners-exclude = [
  "class_g = 'Rofi'"
];

#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

#################################
#   Transparency / Opacity      #
#################################

inactive-opacity = 0.65;
frame-opacity = 1.0;
inactive-opacity-override = false;
active-opacity = 1.0;

inactive-exclude = [
  "class_g = 'firefox'",
  "class_g = 'Rofi'"
];

#################################
#     Background-Blurring       #
#################################
blur-background = true;
blur-method = "dual_kawase";

blur-strength = 5;
blur-whitelist = false;

blur-exclude = [
  "class_g = 'Polybar'"
];

#################################
#       General Settings        #
#################################

daemon = true;

backend = "glx";

log-level = "info";
```

**Comment by allusive-dev** [comment]
Hey @snakebite-382 
I'm sorry about that, Compfy seems to react very violently on some systems in terms of memory and power usage.
Due to Picom releasing v12 soon I don't see a point in further maintaining Compfy since animations will be implemented in upstream
