### ISSUE TITLE
[info] Inclusion into Nixpkgs

### ISSUE THREAD

**Issue by AndersonTorres** [allusive-dev/compfy#59]
Hello! I am AndersonTorres, a Nixpkgs contributor.
I opened this issue to tell compfy devs that I picked this package for inclusion into Nixpkgs.

You can follow it via this link: https://github.com/NixOS/nixpkgs/pull/277916

**Comment by JasperC-Dev** [comment]
Hey @AndersonTorres 
Please refer to #61 for more information but I'd like to let you know this repository has had to be abandoned and won't receive further updates.

**Comment by allusive-dev** [comment]
Hello @AndersonTorres 
No idea how my account is alive but I checked it my email was still in the GitHub system and there we go I'm back apparently.

Yeah there is not point in adding Compfy to Nixpkgs now since soon Picom will implement animations.
