### ISSUE TITLE
Blur not work BSPWM

### ISSUE THREAD

**Issue by Shentxt** [allusive-dev/compfy#65]
## My configurations

blur-background = true;
blur-method = "dual_kawase";
blur-size = 12
blur-deviation = true
blur-strength = 6;
blur-background-frame = true;
blur-background-fixed = true;
blur-kern = "3x3box";
blur-whitelist = true;

## I don't know why the blur doesn't work. I get this error

![Screenshot_2024-02-01-21-58-37_1366x768](https://github.com/allusive-dev/compfy/assets/89170885/2631d0d9-1494-4361-8864-9416c7230626)

**Comment by jasper-at-windswept** [comment]
@Shentxt 
If you are using `blur-whitelist = true;` then you need to pass into a list the windows you want blurred.
Please read the docs:
https://github.com/allusive-dev/compfy/blob/main/man/compfy.md#blur-include
